export const GET_ERRORS = "GET_ERRORS";
export const PUT_USER = "PUT_USER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const POST_LOADING = "POST_LOADING";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";

//WORKERS
export const LOADING_WORKERS = "LOADING_WORKERS";
export const GET_WORKER = "GET_WORKER";
export const GET_WORKERS = "GET_WORKERS";

//WORKER TYPE
export const LOADING_WORKER_TYPES = "LOADING_WORKER_TYPES";
export const ADD_WORKER_TYPE = "ADD_WORKER_TYPE";
export const GET_WORKER_TYPES = "GET_WORKER_TYPES";
export const DELETE_WORKER_TYPE = "DELETE_WORKER_TYPE";

//ADVERTISEMENTS
export const LOADING_ADVERTISEMENTS = "LOADING_ADVERTISEMENTS";
export const ADD_ADVERTISEMENT = "ADD_ADVERTISEMENT";
export const GET_ADVERTISEMENTS = "GET_ADVERTISEMENTS";
export const DELETE_ADVERTISEMENT = "DELETE_ADVERTISEMENT";
